#Application Configuration
server:
  port: 8093
  error:
    include-message: always
    include-binding-errors: always
# ===============================
# DATABASE
# ===============================
spring:
  h2:
  console:
    enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:mem:invoiceDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

# ===============================
# JPA / HIBERNATE
# ===============================
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect

  logging:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

#spring.cloud.config.import-check.enabled=false

#eureka.client.serviceUrl.defaultZone = http://localhost:8099/eureka/

#Feign.hystrix.enabled = true
#management.endpoints.web.exposure.include = "*"